# Generated by Django 4.0.3 on 2022-04-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pending_state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('chat_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temple_island_bot.users')),
            ],
        ),
    ]
